version: '3.9'
services:
  db:
    image: 'postgres'
    ports:
      - '5431:5432'
    environment:
      POSTGRES_PASSWORD: '620602'
      POSTGRES_USER: 'admin'
      POSTGRES_DB: 'test2'
    volumes:
      - data:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
      - ./__tests__:/app/__tests__
    ports:
      - '3001:3000'
volumes:
  data:
